services:
  - type: web
    name: django-saas-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHONPATH
        value: ./backend
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: [] # only internal access

databases:
  - name: django-db
    plan: free
    databaseName: saas_collab_db
    user: saas_user
